// import 'package:threddit_clone/features/home_page/model/newpost_model.dart';

// List<Post> posts = [
//     Post(
//       id: "1",
//       title: "First Post",
//       textBody: "This is the body of the first post.",
//       image: "first_post_image.jpg",
//       nsfw: false,
//       spoiler: false,
//       locked: false,
//       approved: true,
//       postedTime: DateTime.now(),
//       video: null,
//       numViews: 100,
//       commentsCount: 20,
//       userID: User(id: "user1", username: "user1"),
//       subredditID: Subreddit(id: "subreddit1", name: "Subreddit1"),
//       votes: Votes(upVotes: 50, downVotes: 10),
//       parentPost: null,
//     ),
// Post(
//       id: "2",
//       title: "Second Post",
//       textBody: "This is the body of the second post.",
//       image: "second_post_image.jpg",
//       nsfw: false,
//       spoiler: false,
//       locked: false,
//       approved: true,
//       postedTime: DateTime.now(),
//       video: null,
//       numViews: 80,
//       commentsCount: 15,
//       userID: User(id: "user2", username: "user2"),
//       subredditID: Subreddit(id: "subreddit2", name: "Subreddit2"),
//       votes: Votes(upVotes: 40, downVotes: 5),
//       parentPost: null,
//     ),
//   ];