import 'package:threddit_clone/models/post.dart';

List<Post> posts = [
  Post(
    title: "First Post",
    textBody: "This is the text body of the first post.",
    video: null,
    image: "https://example.com/image1.jpg",
    community: "community1",
    spoiler: false,
    nsfw: false,
    locked: false,
    commentsID: ["comment1", "comment2"],
    userID: "user1",
    postedTime: DateTime.now(),
    numViews: 100,
    id: "post1",
    votes: Vote(upvotes: 10, downvotes: 2),
  ),
  Post(
    title: "Second Post",
    textBody: null,
    video: "https://example.com/video1.mp4",
    image: null,
    community: "community2",
    spoiler: true,
    nsfw: false,
    locked: false,
    commentsID: ["comment3"],
    userID: "user2",
    postedTime: DateTime.now(),
    numViews: 50,
    id: "post2",
    votes: Vote(upvotes: 20, downvotes: 5),
  ),
];
