// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
<<<<<<< Updated upstream
        return ios;
      case TargetPlatform.macOS:
        return macos;
=======
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
>>>>>>> Stashed changes
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
<<<<<<< Updated upstream

    apiKey: 'AIzaSyC44i_G-LlgGCuCm3hnkamhgDgLcQ59Uu4',
    appId: '1:492546440281:web:7c6a32e4bc6307877dc548',
    messagingSenderId: '492546440281',
    projectId: 'threadit-c20a3',
    authDomain: 'threadit-c20a3.firebaseapp.com',
    storageBucket: 'threadit-c20a3.appspot.com',
    measurementId: 'G-MFNWEWX467',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAENbXgE0gfxXWXqoaRBoIqJdMjO6WkD1M',
    appId: '1:492546440281:android:ad10abdb97bc59b17dc548',
    messagingSenderId: '492546440281',
    projectId: 'threadit-c20a3',
    storageBucket: 'threadit-c20a3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfJMyQV4JF6bN4Ic8kjc8Ikyj83D_LiCA',
    appId: '1:492546440281:ios:c5a4ccdb9721ba9b7dc548',
    messagingSenderId: '492546440281',
    projectId: 'threadit-c20a3',
    storageBucket: 'threadit-c20a3.appspot.com',

    iosBundleId: 'com.example.thredditApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(

    apiKey: 'AIzaSyCfJMyQV4JF6bN4Ic8kjc8Ikyj83D_LiCA',
    appId: '1:492546440281:ios:de642069bcbb938c7dc548',
    messagingSenderId: '492546440281',
    projectId: 'threadit-c20a3',
    storageBucket: 'threadit-c20a3.appspot.com',

    iosBundleId: 'com.example.thredditApp.RunnerTests',
=======
    apiKey: 'AIzaSyBARS84ojOSU7LKnWnLixIeJT9Vdpl14TI',
    appId: '1:300534889914:web:f973ae37e3d6f220eef183',
    messagingSenderId: '300534889914',
    projectId: 'threddit-clone-app',
    authDomain: 'threddit-clone-app.firebaseapp.com',
    storageBucket: 'threddit-clone-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAxesg2PiZ1v3xq1wmpAXbyN6Pr8wCUcA',
    appId: '1:300534889914:android:92e854a5c84f4c2ceef183',
    messagingSenderId: '300534889914',
    projectId: 'threddit-clone-app',
    storageBucket: 'threddit-clone-app.appspot.com',
>>>>>>> Stashed changes
  );
}
