class Interest {
  const Interest(this.text, this.interestsFirstRow, this.interestsSecondRow);
  final String text;
  final List<String> interestsFirstRow;
  final List<String> interestsSecondRow;
}

const interestsList = [
  Interest('Global Perspectives', [
    'World News',
    'Politics',
    'Business & Finance',
    'Technology',
    'Science',
    'Health',
    'Environment',
    'Education',
    'Law',
    'Crime',
    'Economy',
    'Diplomacy',
    'Social Justice',
    'Human Rights',
    'Global Development',
    'Conflict Resolution',
    'International Relations',
    'Cultural Exchange',
    'Sustainability',
    'Future Trends'
  ], [
    'Geopolitics',
    'Trade',
    'Innovation',
    'Research',
    'Public Health',
    'Climate Change',
    'Literacy',
    'Justice System',
    'Cybersecurity',
    'Social Movements',
    'Poverty Alleviation',
    'International Aid',
    'Diversity & Inclusion',
    'Activism',
    'Emerging Markets',
    'Peacekeeping',
    'Globalization',
    'Renewable Energy',
    'Artificial Intelligence',
    'Bioethics'
  ]),
  Interest('Modern Life', [
    'Fashion & Beauty',
    'Relationships',
    'Parenting',
    'Health & Fitness',
    'Food & Cooking',
    'Travel',
    'Personal Finance',
    'Home & Garden',
    'Pets',
    'DIY & Crafts',
    'Minimalism',
    'Sustainable Living',
    'Urban Planning',
    'Digital Nomadism',
    'Self-Care',
    'Life Hacks',
    'Etiquette',
    'Gardening',
    'Interior Design',
    'Architecture'
  ], [
    'Fashion Trends',
    'Dating',
    'Child Development',
    'Nutrition',
    'Culinary Arts',
    'Adventure Travel',
    'Budgeting',
    'Home Improvement',
    'Animal Welfare',
    'Upcycling',
    'Decluttering',
    'Eco-Friendly Products',
    'Smart Homes',
    'Remote Work',
    'Wellness',
    'Productivity Tips',
    'Social Skills',
    'Landscaping',
    'Home Decor',
    'Green Building'
  ]),
  Interest('Entertainment Showcase', [
    'Movies',
    'TV Shows',
    'Music',
    'Books',
    'Comics & Manga',
    'Anime',
    'Podcasts',
    'Theater',
    'Stand-up Comedy',
    'Celebrity News & Gossip',
    'Film Festivals',
    'Streaming Services',
    'Concerts',
    'Literary Fiction',
    'Graphic Novels',
    'Animation',
    'Audio Dramas',
    'Broadway',
    'Improv Comedy'
  ], [
    'Independent Films',
    'Documentaries',
    'Classical Music',
    'Non-Fiction',
    'Webcomics',
    'Japanese Culture',
    'True Crime Podcasts',
    'Musicals',
    'Open Mic Nights',
    'Award Shows',
    'Short Films',
    'Online Entertainment',
    'Music History',
    'Poetry',
    'Comic Conventions',
    'Studio Ghibli',
    'Educational Podcasts',
    'Experimental Theatre',
    'Satire',
    'Celebrity Interviews'
  ]),
  Interest('Game On!', [
    'Video Games',
    'PC Gaming',
    'Console Gaming',
    'Mobile Gaming',
    'Esports',
    'Gaming News',
    'Game Development',
    'Tabletop Games',
    'Board Games',
    'Card Games',
    'Indie Games',
    'Retro Games',
    'Virtual Reality',
    'Augmented Reality',
    'Competitive Gaming',
    'Game Reviews',
    'Game Design'
  ], [
    'Open World Games',
    'First-Person Shooters',
    'Puzzle Games',
    'Mobile Apps',
    'Live Streaming',
    'Game Guides',
    'Programming',
    'Dungeons & Dragons',
    'Chess',
    'Poker',
    'Sandbox Games',
    'Platformers',
    'Simulation Games',
    'Mobile Esports',
    'Gaming Community',
    'Game Mechanics',
    'Level Design',
    'Character Creation',
    'Collectible Card Games',
    'Board Game Design'
  ]),
  Interest('Sports Arena', [
    'Football',
    'Basketball',
    'Baseball',
    'Soccer',
    'Hockey',
    'Tennis',
    'Golf',
    'MMA',
    'Boxing',
    'Motorsports',
    'Cycling',
    'Swimming',
    'Track & Field',
    'Gymnastics',
    'Volleyball',
    'Rugby',
    'Cricket',
    'Bowling',
    'Extreme Sports'
  ], [
    'American Football',
    'College Basketball',
    'Major League Baseball',
    'International Soccer',
    'Ice Hockey',
    'Grand Slam Tournaments',
    'PGA Tour',
    'UFC',
    'Professional Boxing',
    'Formula 1',
    'Tour de France',
    'Olympic Swimming',
    'Marathons',
    'Artistic Gymnastics',
    'Beach Volleyball',
    'Rugby World Cup',
    'Indian Premier League',
    'Professional Bowling',
    'Skateboarding',
    'Skiing',
    'Paralympic Sports'
  ]),
  Interest('Passion Projects', [
    'Photography',
    'Art & Design',
    'Music Production',
    'Writing & Poetry',
    'Coding & Programming',
    'Learning Languages',
    'History',
    'Science Fiction & Fantasy',
    'Investing',
    'Collecting',
    'Calligraphy',
    'Painting',
    'Podcasting',
    'Creative Writing',
    'Web Development',
    'Jewelry Making',
    'Woodworking'
  ], [
    'Digital Photography',
    'Graphic Design',
    'Music Composition',
    'Journaling',
    'Python',
    'Foreign Languages',
    'Ancient History',
    'Fantasy Novels',
    'Stock Market',
    'Stamp Collecting',
    'Hand Lettering',
    'Watercolor',
    'Audio Editing',
    'Screenwriting',
    'App Development',
    'Metalworking',
    '3D Printing',
    'Creative Coding'
  ]),
  Interest('STEM Frontiers', [
    'Space',
    'Physics',
    'Chemistry',
    'Biology',
    'Mathematics',
    'Engineering',
    'Artificial Intelligence',
    'Robotics',
    'Gadgets',
    'Virtual Reality',
    'Astronomy',
    'Quantum Physics',
    'Organic Chemistry',
    'Genetics',
    'Calculus',
    'Nanotechnology',
    'Bioengineering',
    'Aerospace Engineering'
  ], [
    'Space Exploration',
    'Theoretical Physics',
    'Biochemistry',
    'Evolutionary Biology',
    'Algebra',
    'Civil Engineering',
    'Machine Learning',
    'Automation',
    'Wearable Tech',
    'Metaverse',
    'Astrophysics',
    'Particle Physics',
    'Materials Science',
    'Microbiology',
    'Statistics',
    'Environmental Engineering',
    'Genetic Engineering',
    'Ethical Hacking'
  ]),
  Interest('Humanity & Culture', [
    'History',
    'Philosophy',
    'Psychology',
    'Sociology',
    'Religion',
    'Mythology',
    'Languages',
    'Anthropology',
    'Archaeology',
    'Politics',
    'Ethics',
    'Cognitive Science',
    'Social Psychology',
    'World Religions',
    'Folklore',
    'Linguistics',
    'Cultural Anthropology',
    'Social Work'
  ], [
    'Ancient Civilizations',
    'Existentialism',
    'Developmental Psychology',
    'Cultural Studies',
    'Comparative Religion',
    'Greek Mythology',
    'Endangered Languages',
    'Forensic Anthropology',
    'Paleontology',
    'Political Science',
    'Moral Philosophy',
    'Neuroscience',
    'Social Behavior',
    'Spirituality',
    'Urban Legends',
    'Sociolinguistics',
    'Archaeological Sites',
    'Humanitarian Aid'
  ]),
  Interest('Just for Laughs', [
    'Memes',
    'Funny Videos',
    'Stand-up Comedy',
    'Satire',
    'Dark Humor',
    'Wholesome Memes',
    'Reaction GIFs',
    'Fails & Win',
    'Animals & Pets',
    'Funny Videos',
    'Prank Videos',
    'Comedy Movies',
    'Comedy TV Shows',
    'Cartoons',
    'Webcomics'
  ], [
    'Internet Memes',
    'Viral Videos',
    'Observational Comedy',
    'Parody',
    'Cringe Comedy',
    'Cute Animals',
    'Blooper Reels',
    'Funny Fails',
    'Animal Videos',
    'Stand-up Specials',
    'Sitcoms',
    'Animated Films',
    'Comic Strips',
    'Gag Cartoons',
    'Slapstick',
    'Improvisational Comedy'
  ]),
  Interest(
    'Creative Arts',
    [
      'Painting',
      'Drawing',
      'Sculpture',
      'Photography',
      'Filmmaking',
      'Music Composition',
      'Creative Writing',
      'Dance',
      'Theater',
      'Design',
      'Architecture',
      'Fashion Design',
      'Culinary Arts',
      'Digital Art',
      'Animation',
      'Game Design',
      'Graphic Design',
      'Interior Design',
      'Jewelry Making',
      'Pottery'
    ],
    [
      'Watercolor Painting',
      'Oil Painting',
      'Abstract Art',
      'Portrait Photography',
      'Documentary Filmmaking',
      'Classical Music',
      'Poetry',
      'Ballet',
      'Musical Theater',
      'Industrial Design',
      'Landscape Architecture',
      'Haute Couture',
      'Pastry Arts',
      '3D Modeling',
      'Stop Motion Animation',
      'Indie Game Development',
      'Branding',
      'Home Decor',
      'Metalsmithing',
      'Ceramic Art'
    ],
  ),
];
